{% set name = "ipywidgets_bokeh" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87191fc4ced444daa441186fb2d13c8a30e730ff3fc5b7870748d162ddd73899

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . -vv --no-deps
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - bokeh >=3.4
        - ipykernel >=6,!=6.18.0
        - ipywidgets ==8.*
    test:
      imports:
        - ipywidgets_bokeh
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: ipywidgets-bokeh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - ipywidgets_bokeh

about:
  home: https://github.com/bokeh/ipywidgets_bokeh
  summary: Allows embedding of Jupyter widgets in Bokeh layouts.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
    - hoxbro
