{% set name = "ipywidgets_bokeh" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipywidgets_bokeh-{{ version }}.tar.gz
  sha256: 42f3dbe39bd1618a98f1b9ea43ac2573533fc56badb85fee5145d1235467f636

build:
  number: 1

outputs:
  - name: ipywidgets_bokeh
    script: {{ python }} -m pip install . -vv
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
        - pip
      run:
        - python >=3.9
        - bokeh ==3.*
        - ipykernel ==6.*,!=6.18.0
        - ipywidgets ==8.*
      run_constrained:
        - ipywidgets-bokeh {{ version }}
    test:
      imports:
        - ipywidgets_bokeh
      commands:
        - pip check
      requires:
        - pip

  - name: ipywidgets-bokeh
    requirements:
      run:
        - {{ pin_subpackage('ipywidgets_bokeh', exact=True) }}
    test:
      imports:
        - ipywidgets_bokeh

about:
  home: https://github.com/bokeh/ipywidgets_bokeh
  summary: Allows embedding of Jupyter widgets in Bokeh layouts.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
    - hoxbro
