{% set name = "ipywidgets_bokeh" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 062a1c3ee927831471df2d6438d5e8e5dc668c961192a3b619a0d2e70c8f7901

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . -vv --no-deps
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - bokeh ==3.*
        - ipykernel ==6.*,!=6.18.0
        - ipywidgets ==8.*
        - setuptools
    test:
      imports:
        - ipywidgets_bokeh
      commands:
        - pip check
      requires:
        - pip

  - name: ipywidgets-bokeh
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - ipywidgets_bokeh

about:
  home: https://github.com/bokeh/ipywidgets_bokeh
  summary: Allows embedding of Jupyter widgets in Bokeh layouts.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
    - hoxbro
